---
title: "RWorksheet_SOCO-3_B"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1. Create a data frame using the table below.
#a. Write the codes.
#b. Describe the data. Get the structure or the summary of the data

respondents <- c(1,2,3,4,5,6,7,8,9,10,
                 11,12,13,14,15,16,17,18,19,20)
sex <- c(2,2,1,2,2,2,2,2,2,2,
         1,2,2,2,2,2,2,2,1,2)
fathers_occupation <- c(1,3,3,3,1,2,3,1,1,1,
                        3,2,1,3,3,1,3,1,2,1)
persons_at_home <- c(5,7,3,8,5,9,6,7,8,4,
                     7,5,4,7,8,8,3,11,7,6)
siblings_at_school <- c(6,4,4,1,2,1,5,3,1,2,
                        3,2,5,5,2,1,2,5,3,2)
types_of_houses <- c(1,2,3,1,1,3,3,1,2,3,
                     2,3,2,2,3,3,3,3,3,2)

data <- data.frame(respondents, sex, fathers_occupation, 
                   persons_at_home, siblings_at_school, types_of_houses)
data

#Getting the Structure and summary of the data.
str(data)
summary(data)

#c. Is the mean number of siblings attending is 5?
#No, since the mean based on the data is 2.95 as the display shown.
mean_siblings <- mean(data$siblings_at_school)
mean_siblings == 5
mean_siblings

#d. Extract the 1st two rows and all columns

data[1:2, ]

#e. Extract 3rd and 5th rows with 2nd and 4th columns
data [c(3, 5), c(2, 4)]

#f. Select the variable types of houses then store the vector that results as types_houses. Write the codes.
types_houses <- data$types_of_houses
types_houses

#g. Select only all Males respondent that their father occupation was farmer. Write the codes and its output.

male_farmer <- subset(data, sex == 1 & fathers_occupation == 1)
male_farmer

#h. Select only all females respondent that have greater than or equal to 5 number of siblings attending school. Write the codes and its outputs.
female_5plus <- subset(data, sex == 2 & siblings_at_school >= 5)
female_5plus


```

```{r}
#2. Write a R program to create an empty data frame. Using the following codes:

df = data.frame(Ints=integer(),

Doubles=double(), Characters=character(),
Logicals=logical(),
Factors=factor(),
stringsAsFactors=FALSE)

print("Structure of the empty dataframe:")
print(str(df))

#a. Describe the results.
#The program creates an empty data frame with zero rows but five predefined 
#columns, each assigned a specific data type. The str() output confirms the 
#structure by showing the column names and their corresponding types even though 
#no data is stored yet.
```

```{r}
#3. Create a .csv file of this. Save it as HouseholdData.csv
data <- data.frame(
  Respondents = 1:10,
  Sex = c("Male","Female","Female","Male","Male", "Female","Female","Male",
          "Female","Male"),
  Fathers.Occupation = c(1,2,3,3,1,2,2,3,1,3),
  Persons.at.Home = c(1,2,3,3,1,2,2,3,1,3),
  Siblings.at.School = c(5,7,3,8,6,4,4,2,11,6),
  Types.of.Houses = c("Wood","Congrete","Congrete","Wood","Semi-congrete",
  "Semi-congrete","Wood","Semi-congrete","Semi-congrete","Congrete"),
  stringsAsFactors = FALSE
)

write.csv(data, "HouseholdData.csv", row.names = FALSE)

#a

data <- read.csv("HouseholdData.csv", stringsAsFactors = FALSE)
data


#b.

data$Sex <- factor(data$Sex, levels = c("Male","Female"))
as.integer(data$Sex)

 #c
data$Types.of.Houses <- factor(data$Types.of.Houses,
                               levels = c("Wood","Congrete","Semi-congrete"))
as.integer(data$Types.of.Houses)
#d
data$Fathers.Occupation <- factor(data$Fathers.Occupation,
                                  levels = c(1,2,3),
                                  labels = c("Farmer","Driver","Others"))
as.integer(data$Fathers.Occupation)

#e
subset(data, Sex == "Female" & Fathers.Occupation == "Driver")
#f

subset(data, Siblings.at.School >= 5)

```
