---
title: "RWorksheet_SOCO#2.R"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1. Create a vector using : operator
x <- -5:5
x
```


```{r}
x <- 1:7
x
```

```{r}
#2.* Create a vector using seq() function
seq(1, 3, by=0.2)
```

```{r}
#3. A factory has a census of its workers. There are 50 workers in total. 
#The following list shows their ages:
ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,
22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,
24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,
18)

print(ages[3])

print(ages[c(2, 4)])

print(ages[-1])

```


```{r}
#4.Create a vector x <- c("first"=3, "second"=0, "third"=9). Then named the
#vector, names(x).
x <- c("first"=3, "second"=0, "third"=9)
x
x[c("first", "third")]
#The Output shows only the first and third which the value is 3 and 9.
```


```{r}
#5. Create a sequence x from -3:2.
x <- -3:2
x
x[2] <- 0
x
#The output shows that the element [2] was replaced by 0.
```

```{r}
Month <- c("Jan", "Feb", "March" ,"April" , "May", "June")
Priceperliter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
Liters <- c(25, 30, 40, 50, 10, 45)

fuel <- data.frame(Month, Priceperliter, Liters)
fuel

ave <- weighted.mean(Liters, Priceperliter)
ave
```

```{r}
#7. R has actually lots of built-in data sets. For example, the rivers 
#data “gives the lengths (in miles) of 141 “major” rivers in North America,
#as compiled by the US Geological Survey”.

#a.
data <- c(
  length(rivers),   # number of elements
  sum(rivers),      # sum
  mean(rivers),     # mean
  median(rivers),   # median
  var(rivers),      # variance
  sd(rivers),       # standard deviation
  min(rivers),      # minimum
  max(rivers)       # maximum
)
data
#The output is / [1]    141.0000  83357.0000    591.1844   
#425.0000 243908.4086    493.8708    135.0000   3710.0000
```

```{r}
#8. The table below gives the 25 most powerful celebrities and their annual pay 
#as ranked by the editions of Forbes magazine and as listed on the Forbes.com website.
# Original vectors
Rank <- 1:25
Celebrity <- c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", "Tiger Woods",
               "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the Sopranos",
               "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali",
               "Paul McCartney", "George Lucas", "Elton John", "David Letterman",
               "Phil Mickelson", "J.K. Rowling", "Brad Pitt", "Peter Jackson",
               "Dr. Phil McGraw", "Jay Leno", "Celine Dion", "Kobe Bryant")

Pay <- c(67, 90, 225, 110, 90,
         332, 302, 41, 52,
         88, 55, 44, 55,
         40, 233, 34, 40,
         47, 75, 25, 39,
         45, 32, 40, 31)

forbes <- data.frame(Rank, Celebrity, Pay)
#Modification
forbes[forbes$Rank == 15, "Celebrity"] <- "J.K. Rowling"
forbes[forbes$Rank == 15, "Pay"] <- 90
forbes[forbes$Rank == 19, "Celebrity"] <- "George Lucas"

forbes

#Interpretation 
#After the modification, J.K. Rowling replaced George Lucas at Rank 15 with 
#a pay of 90 million dollars. This change moves her up from Rank 19, showing an
#increase in both influence and financial standing in the Forbes list.
```
